### ISSUE TITLE
Add Microsoft Teams supports ?

### ISSUE THREAD

**Issue by kelplant** [jolicode/secret-santa#150] opened 2020-07-14 14:22 UTC
Hello Jolicode :) /wave
This is a cool project ! Is there any way to add Microsoft Teams implementation ?

https://docs.microsoft.com/fr-fr/microsoftteams/platform/

Would be nice for next Christmas !

**Comment by damienalexandre** [comment] 2020-07-14 15:04
Hi!

It would be very nice I agree, sadly we did not manage to make it work properly so far. I tried the API 2 years ago, I even pushed a branch here: https://github.com/jolicode/secret-santa/compare/ms-teams-support and it worked a bit...

But as stated here: https://github.com/jolicode/secret-santa/issues/55#issuecomment-428637815 I was not confident with Teams API.

I'm closing your issue as it's a duplicate of https://github.com/jolicode/secret-santa/issues/55 - we hope someone can jump in the boat and implement this properly one day 👍 

Cheers

**Closed by damienalexandre** 2020-07-14 15:04 UTC
